APPLICATION_STATUS_ACCEPTED = "accepted"
APPLICATION_STATUS_REJECTED = "rejected"
APPLICATION_STATUS_UPDATE_REQUEST = "update_request"
APPLICATION_STATUS_REVISIONS_REQUIRED = "revisions_required"
APPLICATION_STATUS_PENDING = "pending"
APPLICATION_STATUS_IN_PROGRESS = "in progress"
APPLICATION_STATUS_COMPLETED = "completed"
APPLICATION_STATUS_ON_HOLD = "on hold"
APPLICATION_STATUS_READY = "ready"

APPLICATION_TYPE_UPDATE_REQUEST = "update request"
APPLICATION_TYPE_FINISHED = "finished application/update"
APPLICATION_TYPE_NEW_APPLICATION = "new application"

PROVENANCE_STATUS_REJECTED = "status:rejected"
PROVENANCE_STATUS_ACCEPTED = "status:accepted"

LOCK_APPLICATION = "suggestion"
LOCK_JOURNAL = "journal"

STORE_ANON_DATA = "doaj-anon-data"