# ~~Constants:Config~~
APPLICATION_STATUS_ACCEPTED = "accepted"
APPLICATION_STATUS_REJECTED = "rejected"
APPLICATION_STATUS_UPDATE_REQUEST = "update_request"
APPLICATION_STATUS_REVISIONS_REQUIRED = "revisions_required"
APPLICATION_STATUS_PENDING = "pending"
APPLICATION_STATUS_IN_PROGRESS = "in progress"
APPLICATION_STATUS_COMPLETED = "completed"
APPLICATION_STATUS_ON_HOLD = "on hold"
APPLICATION_STATUS_READY = "ready"

APPLICATION_STATUSES_ALL = [
    APPLICATION_STATUS_ACCEPTED,
    APPLICATION_STATUS_REJECTED,
    APPLICATION_STATUS_UPDATE_REQUEST,
    APPLICATION_STATUS_REVISIONS_REQUIRED,
    APPLICATION_STATUS_PENDING,
    APPLICATION_STATUS_IN_PROGRESS,
    APPLICATION_STATUS_COMPLETED,
    APPLICATION_STATUS_ON_HOLD,
    APPLICATION_STATUS_READY
]

APPLICATION_TYPE_UPDATE_REQUEST = "update_request"
APPLICATION_TYPE_NEW_APPLICATION = "new_application"

INDEX_RECORD_TYPE_UPDATE_REQUEST_UNFINISHED = "Update Request (in progress)"
INDEX_RECORD_TYPE_UPDATE_REQUEST_FINISHED = "Update Request (finished)"
INDEX_RECORD_TYPE_NEW_APPLICATION_UNFINISHED = "Application (in progress)"
INDEX_RECORD_TYPE_NEW_APPLICATION_FINISHED = "Application (finished)"

PROVENANCE_STATUS_REJECTED = "status:rejected"
PROVENANCE_STATUS_ACCEPTED = "status:accepted"

LOCK_APPLICATION = "suggestion"
LOCK_JOURNAL = "journal"

IDENT_TYPE_DOI = "doi"
LINK_TYPE_FULLTEXT = "fulltext"

# ~~-> Todo:Service~~
TODO_MANED_STALLED = "todo_maned_stalled"
TODO_MANED_FOLLOW_UP_OLD = "todo_maned_follow_up_old"
TODO_MANED_READY = "todo_maned_ready"
TODO_MANED_COMPLETED = "todo_maned_completed"
TODO_MANED_ASSIGN_PENDING = "todo_maned_assign_pending"

EVENT_ACCOUNT_CREATED = "account:created"
EVENT_APPLICATION_STATUS = "application:status"
EVENT_APPLICATION_ASSED_ASSIGNED = "application:assed:assigned"

NOTIFICATION_CLASSIFICATION_STATUS_CHANGE = "status_change"
NOTIFICATION_CLASSIFICATION_ASSIGN = "assign"
NOTIFICATION_CLASSIFICATION_CREATE = "create"