#!/bin/bash
# Edit this file to introduce tasks to be run by cron.
# 
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
# 
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').# 
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
# 
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
# 
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
# 
# For more information see the manual pages of crontab(5) and cron(8)
# 
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m      h      dom      mon      dow      command
  30     0      *        *        *        export NOW=`date +\%F_\%H\%M\%S` ; export YESTERDAY_DATE=`date -d yesterday +\%F`; export DOAJENV=production ; echo -e "\n\nstart timestamp $NOW" >> /home/cloo/cron-logs/doaj-article-history-cleanup.log && cd /home/cloo/appdata/doaj/history/article && tar -czf "article-$YESTERDAY_DATE.tar.gz" "$YESTERDAY_DATE/" >> /home/cloo/cron-logs/doaj-article-history-cleanup.log 2>&1 && s3cmd -c ~/.s3cfg put "article-$YESTERDAY_DATE.tar.gz" "s3://doaj-sync-$DOAJENV/" >> /home/cloo/cron-logs/doaj-article-history-cleanup.log 2>&1 && rm -r "$YESTERDAY_DATE" >> /home/cloo/cron-logs/doaj-article-history-cleanup.log 2>&1 && rm "article-$YESTERDAY_DATE.tar.gz" >> /home/cloo/cron-logs/doaj-article-history-cleanup.log 2>&1

