version: 2.1
orbs:
  python: circleci/python@2.1.1
  browser-tools: circleci/browser-tools@1.2.3

executors:
  test-executor:
    docker:
      - image: cimg/python:3.12
        environment:
          DOAJENV: test
      - image: cimg/redis:6.2.14
      - image: opensearchproject/opensearch:1.3.20
        environment:
          - plugins.security.disabled: true
          - transport.host: localhost
          - discovery.type: single-node
    working_directory: ~/doaj

commands:
  install-and-prepare:
    description: "Install dependencies and prepare the doaj test env"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - python/install-packages:
          pkg-manager: pip-dist
          pip-dependency-file: setup.py
          path-args: .[test]
      - run:
          name: Prepare doaj env for tests
          command: |
            echo "ELASTICSEARCH_HOSTS = [{'host': 'localhost', 'port': 9200}]" > test.cfg
            echo "DEFAULT_INDEX_SETTINGS = { 'number_of_shards': 1, 'number_of_replicas': 0, 'analysis': { 'analyzer': { 'ascii_folded': { 'tokenizer': 'standard', 'filter': ['lowercase', 'asciifolding'] } } } }" >> test.cfg
            echo "PASSWORDLESS_ENCRYPTION_KEY = 'KaqSOF70jLVn8E9Pjq4PXO_TNbR_K-96J2dYwzhRJDo='" >> test.cfg
            python portality/cms/build_fragments.py
            python portality/cms/build_sass.py

jobs:
  unit-tests:
    executor: test-executor
    parallelism: 4
    steps:
      - install-and-prepare
      - run:
          name: Run unit tests
          command: |
            TESTS=$(circleci tests glob "doajtest/unit/**/*.py" | circleci tests split)
            pytest -v --color=yes --code-highlight=yes --log-level=DEBUG --junitxml=test-results/doajtest-unit.xml $TESTS
      - store_test_results:
          path: test-results

  selenium-tests:
    executor: test-executor
    parallelism: 1
    steps:
      - install-and-prepare
      - run:
          name: Env for selenium
          command: |
            echo "SELENIUM_REMOTE_URL = ''" >> test.cfg
            echo "SELENIUM_DOAJ_HOST = 'localhost'" >> test.cfg
            echo "SELENIUM_HEADLESS = True" >> test.cfg
      - browser-tools/install-chrome
      - run:
          name: List current env
          command: |
            cat test.cfg
            google-chrome --version
      - run:
          name: Run selenium tests
          command: |
            TESTS=$(circleci tests glob "doajtest/seleniumtest/*.py" | circleci tests split)
            pytest -v -s --color=yes --code-highlight=yes --log-level=DEBUG --junitxml=test-results/doajtest-selenium.xml $TESTS
      - store_test_results:
          path: test-results

workflows:
  tests:
    jobs:
      - unit-tests:
          filters:
            branches:
              ignore:
                - static_pages
      - selenium-tests:
          filters:
            branches:
              ignore:
                - static_pages
