#!/bin/bash
# Edit this file to introduce tasks to be run by cron.
# 
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
# 
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').# 
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
# 
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
# 
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
# 
# For more information see the manual pages of crontab(5) and cron(8)
# 
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# m     h      dom     mon     dow     command
  0     6      *       *       *       export NOW=`date +\%F_\%H\%M\%S` ; export SNAPSHOT="snapshot_"`date +\%F_\%H\%M`; echo -e "\n\nstart timestamp $NOW with snapshot name $SNAPSHOT" >> /home/cloo/cron-logs/es_backups.log && curl -s -XPUT "http://gateway:9200/_snapshot/doaj_s3/$SNAPSHOT" >> /home/cloo/cron-logs/es_backups.log 2>&1
 19     11,23  *       *       *       export NOW=`date +\%F_\%H\%M\%S` ; echo -e "\n\nstart timestamp $NOW" >> /home/cloo/cron-logs/letsencrypt-autorenew.log && cd /opt/letsencrypt && ./letsencrypt-auto renew >> /home/cloo/cron-logs/letsencrypt-autorenew.log 2>&1 && sudo nginx -t >> /home/cloo/cron-logs/letsencrypt-autorenew.log 2>&1 && sudo nginx -s reload >> /home/cloo/cron-logs/letsencrypt-autorenew.log 2>&1
 30     3      *       *       7       . /home/cloo/.doaj_duplicity_credentials ; duplicity full --s3-use-new-style --encrypt-key=98FADACE --exclude /home/cloo/repl/.git /home/cloo/repl s3+http://doaj-duplicity >> /home/cloo/cron-logs/duplicity.log 2>&1 && duplicity remove-all-but-n-full 4 --s3-use-new-style --force s3+http://doaj-duplicity >> /home/cloo/cron-logs/duplicity.log 2>&1
 30     3      *       *       1-6     . /home/cloo/.doaj_duplicity_credentials ; duplicity incr --s3-use-new-style --encrypt-key=98FADACE --exclude /home/cloo/repl/.git /home/cloo/repl s3+http://doaj-duplicity >> /home/cloo/cron-logs/duplicity.log 2>&1
